/**
 * Constantes de códigos de error para APIs
 * Códigos estandarizados para identificar tipos de error
 */

/**
 * Códigos de error de validación
 */
export const ERROR_CODES = {
  // Validación
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  FIELD_REQUIRED: 'FIELD_REQUIRED',
  FIELD_INVALID: 'FIELD_INVALID',
  
  // Autenticación y Autorización
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  
  // Recursos
  NOT_FOUND: 'NOT_FOUND',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  CONFLICT: 'CONFLICT',
  DUPLICATE_KEY: 'DUPLICATE_KEY',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
  
  // Rate Limiting
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  
  // Servidor
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  
  // Base de datos
  DATABASE_ERROR: 'DATABASE_ERROR',
  DB_CONNECTION_ERROR: 'DB_CONNECTION_ERROR',
  DB_QUERY_ERROR: 'DB_QUERY_ERROR',
  DB_TRANSACTION_ERROR: 'DB_TRANSACTION_ERROR',
  
  // Servicios externos
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  EXTERNAL_SERVICE_TIMEOUT: 'EXTERNAL_SERVICE_TIMEOUT',
  BAD_GATEWAY: 'BAD_GATEWAY',
  GATEWAY_TIMEOUT: 'GATEWAY_TIMEOUT',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];

/**
 * Claves de mensajes de error (mapean a los archivos i18n)
 */
export const ERROR_MESSAGE_KEYS = {
  // Validación
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  
  // Autenticación
  UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  FORBIDDEN: 'AUTH_FORBIDDEN',
  TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  
  // Recursos
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  DUPLICATE: 'DB_DUPLICATE_KEY',
  UNPROCESSABLE: 'UNPROCESSABLE_ENTITY',
  
  // Rate Limiting
  RATE_LIMIT: 'RATE_LIMIT_EXCEEDED',
  
  // Servidor
  SERVER_ERROR: 'SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  TIMEOUT: 'TIMEOUT_ERROR',
  
  // Base de datos
  DB_ERROR: 'DB_ERROR',
  DB_CONNECTION: 'DB_CONNECTION_ERROR',
  DB_QUERY: 'DB_QUERY_ERROR',
  
  // Servicios externos
  EXT_SERVICE_ERROR: 'EXT_SERVICE_ERROR',
  EXT_SERVICE_UNAVAILABLE: 'EXT_SERVICE_UNAVAILABLE',
} as const;

export type ErrorMessageKey = typeof ERROR_MESSAGE_KEYS[keyof typeof ERROR_MESSAGE_KEYS];
